name: Pinball Design
favicon: null
layout_spectrum: 0.8579439441673458
typography_spectrum: 0.4958987033460289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8582672695629299
  lightness: 0.6964634153991938
  saturation: 0.46904205181635916
  rhythmicContrast: 0.5711826386395842
purpose: []
