layout_spectrum: 0.7569643359165639
typography_spectrum: 0.9560702778398991
color:
  saturation: 0.3776475782506168
  brandStrength: 0.14937615115195513
  rhythmicContrast: 0.9477511395234615
  brandColors:
    - '#C4EBDA'
    - '#000000'
    - '#CCA444'
    - '#C640CD'
    - '#836A99'
  lightness: 0.3732358345296234
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Pinball Design
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: from web designer to pinball designer
purpose: []
