name: Pinball Design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4958987033460289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#414141'
    - '#828282'
    - '#a4a4a4'
  brandStrength: 0.75
  lightness: 0.6964634153991938
  saturation: 0.46904205181635916
  rhythmicContrast: 0.5711826386395842
purpose: []
