name: Pinball Design
favicon: null
layout_spectrum: 0.53825
typography_spectrum: 0.38564
title: from web designer to pinball designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#fffffd'
    - '#ff00ff'
    - '#ff860c'
    - '#6b4c21'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
